# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: List files
        run: ls -la
      - name: Check pnpm-lock.yaml
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            echo "pnpm-lock.yaml found"
            ls -l pnpm-lock.yaml
          else
            echo "pnpm-lock.yaml NOT found"
          fi
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            echo "Installing with frozen lockfile"
            pnpm install --frozen-lockfile
          else
            echo "Installing without frozen lockfile"
            pnpm install
          fi
      - name: Run tests
        run: pnpm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: List files
        run: ls -la
      - name: Check pnpm-lock.yaml
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            echo "pnpm-lock.yaml found"
            ls -l pnpm-lock.yaml
          else
            echo "pnpm-lock.yaml NOT found"
          fi
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
      - name: Install dependencies
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            echo "Installing with frozen lockfile"
            pnpm install --frozen-lockfile
          else
            echo "Installing without frozen lockfile"
            pnpm install
          fi
      - name: Publish to npm
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
